### PR TITLE
Access complete account information

### PR DESCRIPTION
**Pull request by jazzboME**
major:
ref: #72  
desc: Accesses complete account information by aligning the structs to what is currently returned by the api. Adds support for the fields= parameter which allows for GetAccount() or GetAccounts() to specify "positions."

Quick code to pull accounts and position informtion
```
acs, err := agent.GetAccounts("positions")
if err != nil {
	fmt.Println(err)
}
for _, ac := range acs {
	fmt.Printf("Account: %s\n", ac.SecuritiesAccount.AccountNumber)
	for _, position := range ac.SecuritiesAccount.Positions {
		quote, err := agent.GetQuote(position.Instrument.Symbol)
		var mark = 0.00
		if err == nil {
			switch quote.AssetMainType {
			case "MUTUAL_FUND":
				mark = quote.Close
			default:
				mark = quote.Mark
			}
		}	
		fmt.Printf(" %s %.4f @ $%.2f $%.2f\n", position.Instrument.Symbol, position.LongQuantity, mark, position.MarketValue)
	}
}
```

### CODE REVIEW

**Comment by samjtro** [comment]
sorry i took so long with this. do you have any experience with error wrapping in prod? is the approach you took in this commit generally reflective of the industry standard?

https://github.com/go-schwab/trader/commit/af97570e220b08a75de7d569fd0d46cec7d0438e

**Comment by jazzboME** [comment]
Yeah, so I made that adjustment in my fork because I was finding that it was trying to aggressively `Reinitiate()` when maybe the problem was a simple validation error (400) from intentionally trying different rogue value to the fields= parameter, not because I was logged out.  So while it's in my prod branch, that was more of a quick and dirty fix to get around that. Really it's only 401 responses that should need to reauthorize, but ultimately I was thinking it was better to have the package pass back what it knows and let the app decide how to proceed.

----

As far as error wrapping, from my understanding that is probably what we should do here rather than using `IsErrNil() `and potentially stopping with a `log.Fatalf()`.

So if we were to wrap the errors maybe it would look more like:
```
default:
	body, err := io.ReadAll(resp.Body)
        if err != nil {
            return nil, fmt.Errorf("%d response, but could not read body: %w", resp.StatusCode, err)
        }
	var errorMessage ErrorMessage
	err = sonic.Unmarshal(body, &errorMessage)
	if err != nil {
            return nil, fmt.Errorf("%d response, but could not unmarshall: %w", resp.StatusCode, err)
        }
	return nil, fmt.Errorf("server Response: %d: %s", resp.StatusCode, errorMessage.Message)
```
The %w verb would wrap the error and the caller could unwrap that.

----

If we wanted to go big, the other option is that the package could define a set of custom errors and make them available to the user -- then the user could potentially use `errors.Is()`

```
     if errors.Is(err, ErrNeedReAuthorization) {
	... application could inform the user and ask for input before initiating the process again
     } 
```

I wrote up a quick example of what a custom error system might do, including a custom error struct, custom error messages, and two examples of errors.Is(), and how the handler might be able to leverage that to pass back more information to the caller: https://go.dev/play/p/tAJIlc1zFcL  

https://go.dev/blog/go1.13-errors is the standard intro to error wrapping. Ultimately industry standard is more or less to wrap when you need to and always avoid wrapping implementation details.

**Comment by samjtro** [comment]
took some time so i could properly understand error wrapping as i hadn't really gotten into it yet - i like the approach dapr uses, creating custom errors is definitely the best way forward. im going to get this merged, and then create a new issue where we can work on creating a robust error handling system.

thanks for your input, it is very much appreciated!

**Comment by samjtro** [comment]
@jazzboME to avoid messing around with these conflicts, would you mind creating a new PR main -> main? sorry for the hassle...

**Comment by jazzboME** [comment]
@samjtro Just getting back to this -- but I believe I have resolved all of the conflicts now.

**Comment by samjtro** [comment]
not sure how, but during the conflict merge an unnecessary line got added back into utils.go ... not to worry, i have some pending changes so i'll remove it before the next release. 

thanks so much again for your contribution, much appreciated! feel free to contribute anything else you'd like!

**Review by samjtro — APPROVED** [review]
fix Reinitate @ 258 before next release: https://github.com/go-schwab/trader/issues/76

**Pull request closed without merging**
